### ISSUE TITLE
Unify prop names across react-tiny-libraries

### ISSUE THREAD

**Issue by bardsol** [asbjornh/react-tiny-transition#1] opened 2019-02-16 09:37 UTC
react-tiny-transition: classNames
react-tiny-crossfade: transitionClassNames

**Comment by asbjornh** [comment] 2019-02-17 12:21
Duplicate of https://github.com/asbjornh/react-tiny-crossfade/issues/2

**Closed as completed by asbjornh** 2019-02-17 12:21 UTC
